### ISSUE TITLE
WindowsStoreProxy.xml data must be provided as string, make a GUI

### ISSUE THREAD

**Issue by felixrieseberg** [felixrieseberg/WinBridge#1]
...which is obviously ugly. 

Okay fix: Allow users to have their own WindowsStoreProxy.xml in the Unity Project folder
Better fix: Allow creation using Unity GUI

**Comment by dwcares** [comment]
@KatVHarris  is this something you can help out in  your efforts to build out the Unity test code?

**Comment by dwcares** [comment]
Here's another idea. Create a new object types: WinControls.Store.TestApp and WinControls.Store.TestProduct. Make EnableDebugWindowsStoreProxy take the TestApp object, and an optional number of TestProduct objects. On the PCL side we build the XML string and write it to disk.

this might be more conusive to UI builders as well in the future

**Comment by dwcares** [comment]
filed a separate issue to create an object model for testapp and testproducts to use in lieu of the XML. this issue will track the UI builder. 

moved this to the v1 milestone since it isn't blocking beta.

**Comment by dwcares** [comment]
fixed by felix in his latest release! and then some...
